<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" tests="8" skipped="8" failures="0" errors="0" timestamp="2016-11-10T07:37:53" hostname="XB-20161010YVDY" time="0.006">
  <properties/>
  <testcase name="asyncMethodReturningFutureGetsRoutedAsynchronouslyAndReturnsAFuture" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.003">
    <skipped/>
  </testcase>
  <testcase name="exceptionHandlerCalled" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="syncMethodGetsRoutedSynchronously" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="methodReturningFutureInAsyncClassGetsRoutedAsynchronouslyAndReturnsAFuture" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="qualifiedAsyncMethodsAreRoutedToCorrectExecutor" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="asyncMethodGetsRoutedAsynchronously" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="exceptionHandlerNeverThrowsUnexpectedException" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="voidMethodInAsyncClassGetsRoutedAsynchronously" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
