<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.dao.support.DataAccessUtilsTests" tests="10" skipped="0" failures="0" errors="0" timestamp="2016-11-10T07:44:15" hostname="XB-20161010YVDY" time="0.008">
  <properties/>
  <testcase name="withString" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withInteger" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="exceptionTranslationWithNoTranslation" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="withDate" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.005"/>
  <testcase name="withLong" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="withTooLargeCollection" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.002"/>
  <testcase name="withSameIntegerInstanceTwice" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="withEmptyCollection" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="withEquivalentIntegerInstanceTwice" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="exceptionTranslationWithTranslation" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
